version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - ./main.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/fmh-web/dist
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"