name: Run tests, build docker image and deploy

on:
  push:
    branches: ["main", "main_v2"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Build
      with:
        node-version: 16
        cache: 'npm'
      run: npm run build

    - name: Log in to the Container registry
      uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v4
    #   with:
    #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@4c2810ab91206d25f3659f1d071b3b189e14ae1c
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }},ghcr.io/fmh-charity/fmh-backend:latest
    #     labels: ${{ steps.meta.outputs.labels }}

    # - name: Deploy
    #   uses: appleboy/ssh-action@v0.1.4
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     port: ${{ secrets.REMOTE_PORT }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: 'cd /usr/src/docker && docker-compose stop && yes | docker-compose pull && docker-compose up -d'
